### ISSUE TITLE
[Messenger][4.3] Tracker for changes

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#11236]
A lot of new things have happened in Messenger for 4.3. This is a meta issue to try to track then:

* [x] New PHP Serializer symfony/symfony#29958
* [x] LoggingMiddleware is deprecated symfony/symfony#30539
* [x] new event dispatched when sending a message symfony/symfony#30650
* [x] Better output when you run `messenger:consume` symfony/symfony#29303
* [x] Command was renamed/shortened to `messenger:consume` Done in #11262
* [x] MessageBus::dispatch() accepts Envelopes are 2nd arg symfony/symfony#30707
* [x] Envelope 2nd constructor arg changed symfony/symfony#30707
* [x] Command to setup transports symfony/symfony#29476
* [x] Retry support - symfony/symfony#30557
* [x] ReceiverInterface methods changed - symfony/symfony#30557 and symfony/symfony#30708 - also a few behavioral things changed inside them
* [x] `UnrecoverableMessageHandlingException` can be thrown in handler to fail and avoid retry - symfony/symfony#30557
* [x] Ability to dispatch a message from within a message and have it handled in a separate Doctrine transaction symfony/symfony#28849
* [x] prefetching option symfony/symfony#30671
* [x] New messenger:stop-workers Command symfony/symfony#30754
* [x] New way to see size of messages in a transport symfony/symfony#30757
* [x] New sync transport symfony/symfony#30759
* [x] Failed message handling symfony/symfony#30970
* [x] multiple queues support for amqp with routing key - symfony/symfony#30008
* [x] Allows to register handlers on a specific transport symfony/symfony#30958
* [x] support for handling multiple transports in one worker in a prioritized way. See this comment and attached PR: https://github.com/symfony/symfony/pull/30708#issuecomment-489483674
* [x] RoutableMessageBus route to default bus symfony/symfony#31288
* [x] Doctrine ping connection middleware symfony/symfony#31061
* [x] Add WorkerStoppedEvent symfony/symfony#31282
* [x] New middleware (not important unless we're documenting all of them somewhere) - symfony/symfony#31425 (there are also other new middleware, which hopefully are mentioned here)
* [x] `send_and_handle` messenger routing got removed in favor of SyncTransport https://github.com/symfony/symfony/pull/31454

**Comment by Tobion** [comment]
[ ] `send_and_handle` messenger routing got removed in favor of SyncTransport https://github.com/symfony/symfony/pull/31454
