### ISSUE TITLE
[Doctrine] Reword the docs about Doctrine

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#12327]
This is a meta-issue to link to all the pull requests related to this:

* [x] Reworded the intro of the article (#12314)
* [x] Merge all articles about "database + testing" (#12317)
* [x] Remove the "registration form" article (#12326)
* [x] Merge all articles about "database + sessions" (#12325)
* [x] Merge all articles about "Doctrine events" (#12328)
* [x] Moved the Doctrine Extensions to the main Doctrine article (#12332)

**Comment by javiereguiluz** [comment]
Closing as fixed because all the related PR are merged.
