### ISSUE TITLE
Update book to comply with best practices

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony-docs#4431]
Some people wanted to follow the progress, so I've created a task list for at least the book articles. The quick tour will be updated by #4374 and the cookbook will not be as important as these other 2 sections, they'll properbly follow after 2.6 is released.

I've ordered them on priority.

* [x] Controller (fixed by #4427 and #4433)
* [x] Templating (fixed by #4427)
* [x] Routing (fixed by #4427)
* [x] From Flat to Sf2 (fixed by #4427)
* [x] Page creation (see #4685, #4687 and #4690)
* [x] Http fundamentals (see #4507)
* [x] Doctrine (fixed by #4507)
* [x] Form (fixed by #4507)
* [x] Security (no changes needed, see https://github.com/symfony/symfony-docs/issues/4431#issuecomment-112465196)
* [x] Validation (fixed by #4779)
* [x] Testing (fixed by #4779)
* [x] Propel (fixed by #4779)
* [x] Http Cache (fixed by #4779)

**Comment by javiereguiluz** [comment]
@WouterJ I've reviewed the chapter about Security and I've found no changes needed to comply with the new best practices. If you agree, you probably can update the TODO list of this PR to mark *Security* as *"done"*. Thanks.

**Comment by xabbuh** [comment]
I agree and checked the item.

**Comment by WouterJ** [comment]
I think we're ready here
