### ISSUE TITLE
extended routing cookbook article

### ISSUE THREAD

**Issue by dbu** [symfony/symfony-docs#5709]
as discussed on twitter a while ago, i am looking into writing a cookbook article on additional things / alternatives to the standard symfony router. i post a sketch for the article here and hope we can discuss it a bit before i write it out in detail:
- [x] Review routing component documentation #6023
  - Routing is not complicated: RequestMatcherInterface: Request => array with routing information
- [x] Review http://symfony.com/doc/current/cookbook/routing/custom_route_loader.html (those routes are still cached in prod environment) #6022
- [x] Translating routes for multilanguage sites
  - i18n routers to translate URLs (https://packagist.org/search/?q=i18n-routing => jms, besimple, any others to mention?)
- [x] Integrating a custom router with symfony #6020
  - CMF ChainRouter when you write your own router. e.g. legacy application
- [x] Looking up routes dynamically from a database (fix #2186) #6021
  - Routes from a database: CMF DynamicRouter. do not need to clear route cache on each edit. if the URL has an index, matching should be almost O(1) even for large number of routes

/cc @weaverryan @WouterJ

**Comment by weaverryan** [comment]
@dbu I know you've done a lot of non-traditional things with routes, so I think you'd be a perfect person to add this. 

I think this should actually be a few cookbook articles - because I want them to be findable, instead of being put together into some big article (e.g. "Custom route loaders and other cool routing stuff"). In other words, we need to think of a few  "How do I do X?" titles that you'd use for these articles, and let that drive the content. For example, the first bullet is interesting, but it's not obvious where this would fit or who would come and look for it (but maybe it fits in the routing component?)

**Comment by dbu** [comment]
i was thinking of kind of a "routing book" but your point is valid. i split this into separate points now (edited the description).

if you have further input, please tell. if this is ok, which version should i work on? 2.7? or even 2.3?

**Comment by dbu** [comment]
of course i will do one pull request per bullet point. i can also review the existing docs for 2.7 and create new doc against master - whatever makes the most sense.

**Comment by xabbuh** [comment]
We should try to create articles that are compatible with Symfony 2.3 (of course we can update them after merging branches up if things are easier/better/whatever in Symfony 2.7 or higher).

**Comment by weaverryan** [comment]
:+1:

**Comment by dbu** [comment]
did PRs for 4 of the 5 points. once done, i could also do #5747 (load routes from service)
