### ISSUE TITLE
YAML dumper flags

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#6226]
symfony/symfony#17578 introduces the possibility to customise the dumped YAML string by passing a bit field of dumper flags.

Symfony 3.1 introduces quite some options that you can use to customise the behaviour of both the parser and the dumper (and also added some more additional features):
- [x] `Yaml::DUMP_OBJECT` toggles object support in the dumper  (symfony/symfony#17578)
- [x] `Yaml::PARSE_EXCEPTION_ON_INVALID_TYPE`, `Yaml::PARSE_OBJECT`, and `Yaml::PARSE_OBJECT_FOR_MAP` replace the previous boolean arguments of the YAML parser (symfony/symfony#17730)
- [x] `Yaml::DUMP_EXCEPTION_ON_INVALID_TYPE` replaces the old boolean parameter (symfony/symfony#17743)
- [x] parse and dump `DateTime` instances (symfony/symfony#17836)
- [x] Support for parsing and dumping base64 encoded binary data (symfony/symfony#17863).
- [x] dump PHP objects as YAML maps (symfony/symfony#17728)
- [x] option to dump multi line strings as literal scalar blocks (symfony/symfony#17943)

**Comment by HeahDude** [comment]
Has anyone started to work on this one yet? It would be very nice to have this doc!

I can try to give it some time this week end if you want.

**Comment by xabbuh** [comment]
@HeahDude Feel free to do so. I didn't work on this yet. You can use [this blog post](http://symfony.com/blog/new-in-symfony-3-1-customizable-yaml-parsing-and-dumping) as a starting point.

**Comment by javiereguiluz** [comment]
Closing as fixed because the last missing flags were documented in #9205.
