### ISSUE TITLE
Fix the Symfony Docs build issues

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7268]
## The problem

We currently have some Symfony Documentation generation issues. Internally, for the symfony.com website, we have made some ugly hacks and patches to solve it (but this causes other problems in the navigation and breadcrumbs). But for the PDF docs we cannot solve these issues.

This picture summarizes the problem:

![symfony_doc](https://cloud.githubusercontent.com/assets/73419/21233626/226163fa-c2f0-11e6-8e3b-2b8d9a962827.png)

The problem is that for the generation tool (Sphinx), the entire Symfony Docs is just 1 HUGE book. Everything is linked. The "Next Page" and "Previous Page" go from 1 book to another. We cannot generate single PDFs for each book.

## The solution

If anyone has experience with Sphinx, please help us solve this problem. How can you know if you have solved it? Easy: generate the Symfony Docs locally as follows and see if different books keep linking between them or not:

```
$ pip install sphinx~=1.3.0 git+https://github.com/fabpot/sphinx-php.git
$ cd symfony-docs/_build
$ make html
# docs are generated in ./html directory
```

## Related issues

This is a meta-issue to fix all the issues related to PDF contents:

- [ ] [No PDF generated for Symfony CMF Bundles, Components, Cookbook](https://github.com/symfony/symfony-docs/issues/5048)
- [ ] [The components PDF is partialy rendered](https://github.com/symfony/symfony-docs/issues/6779)
- [ ] [Broken link for CMF docs](https://github.com/symfony/symfony-docs/issues/7002)
- [ ] [Symfony Cookbook 3.2 PDF documentation not available](https://github.com/symfony/symfony-docs/issues/7232)

**Comment by javiereguiluz** [comment]
Some more examples of the problems we're facing. If we build an individual book as follows:

```
$ sphinx-build create_framework/ _build/html/ -c _build/
```

The book is build independently from others ... but (obviously) none of the cross-references will work. For example:

```
create_framework/http_kernel_controller_resolver.rst:152: WARNING: unknown document: /controller/service
```

And the original content:

```rst
.. note::

    [...]
    is enhanced to support :doc:`controllers as services </controller/service>`;
    and ``getArguments()`` provides an extension point to alter or enhance
    the resolving of arguments.
```

The `controllers as services` content is displayed as a regular text and not as a link to the other page.

**Comment by hason** [comment]
It might help:
- http://www.sphinx-doc.org/en/1.5.1/ext/intersphinx.html
- http://www.sphinx-doc.org/en/1.5.1/ext/extlinks.html

**Comment by javiereguiluz** [comment]
I'm closing this old issue because we're working on a radically different approach to solve this issue. Thanks!
