### ISSUE TITLE
Improve the file uploading documentation

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8255]
We have a lot of issues related to file uploading. Let's merge them all in this meta-issue so we can coordinate the changes better:

* [ ] Stop using entities + form to upload and persist the file upload. Use a DTO + form instead. #6753
* [ ] Explain how to upload multiple files at once. #5603
* [ ] Better explain the way we manage uploaded file extension and MIME type ... and the difference between what the client send and what we guess. #2542
* [ ] There's a bug with the breadcrumb of the file upload article. #7606
* [ ] Mention VichUploaderBundle and entity listeners. #7818
* [ ] How to create fake files for tests. #5346
* [ ] Use a data transformer. #11158
* [ ] File upload guide recommends insecure behaviour #12192
* [ ] [Form] Upload file edit example tip is not needed #13697

**Comment by darius-v** [comment]
https://symfony.com/doc/current/controller/upload_file.html

Here when you do as documentation says, you get an error:

> Class Symfony\Component\Form\AbstractType not found
The problem is - it is not told that symfony/form should be installed. 

https://stackoverflow.com/questions/47853790/symfony-4-class-symfony-component-form-abstracttype-not-found/47853846#47853846

**Comment by OlivierToussaint** [comment]
The documentation don't work with php 7.1 

```
public function getBrochure(): ?string
    {
        return $this->brochure;
    }

    public function setBrochure(string $brochure): self
    {
        $this->brochure = $brochure;

        return $this;
    }
```

in Form we have : 
```
            ->add('brochure', FileType::class, array('label' => 'Brochure (PDF file)'))
```
getBrochure waiting for a string and I receive FileType


in the listener we have 

```
// src/EventListener/BrochureUploadListener.php
namespace App\EventListener;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Doctrine\ORM\Event\LifecycleEventArgs;
use Doctrine\ORM\Event\PreUpdateEventArgs;
use App\Entity\Product;
use App\Service\FileUploader;

class BrochureUploadListener
{
    private $uploader;

    public function __construct(FileUploader $uploader)
    {
        $this->uploader = $uploader;
    }

    public function prePersist(LifecycleEventArgs $args)
    {
        $entity = $args->getEntity();

        $this->uploadFile($entity);
    }

    public function preUpdate(PreUpdateEventArgs $args)
    {
        $entity = $args->getEntity();

        $this->uploadFile($entity);
    }

    private function uploadFile($entity)
    {
        // upload only works for Product entities
        if (!$entity instanceof Product) {
            return;
        }

        $file = $entity->getBrochure();

        // only upload new files
        if ($file instanceof UploadedFile) {
            $fileName = $this->uploader->upload($file);
            $entity->setBrochure($fileName);
        }
    }
}
```
Same issue here getBrochure can't be instances UploadedFile because it's a string.

**Comment by HeahDude** [comment]
Thanks @OlivierToussaint for the report! Fortunately this is already fixed by #9079.

**Comment by OlivierToussaint** [comment]
Np, but ```getBrochure``` in Entity is a string or a File ? In your PR I don't see any change to the entity. 
For me it's a string ```@ORM\Column(type="string")```and in your PR it's a File or UploadFile, I think it will not work.

**Comment by tlarsonlgdor** [comment]
The Symfony "How to Upload Files" instructions are incorrect. See:
[https://github.com/symfony/symfony-docs/pull/9891](url).
These instructions are in conflict with the Symfony FileType Field at:
[https://symfony.com/doc/current/reference/forms/types/file.html](url).
Also, a number of stack overflow responses to the issue solve the problem (using the instructions provided by the FileType Field page):
[https://stackoverflow.com/questions/49604601/call-to-a-member-function-guessextension-on-string](url)
[https://stackoverflow.com/questions/50962366/symfony-4-file-upload-not-working](url)
[https://stackoverflow.com/questions/51657525/symfony-4-error-when-uploading-file](url)

**Comment by xabbuh** [comment]
Sadly, only one of the linked questions on StackOverflow contained the code of the underlying entity class. But in that example the argument of the setter method for the file was type hinted with `string` which means that every time the form is submitted the uploaded file will be cast to a string which leads to this error.

**Comment by OlivierToussaint** [comment]
This PR in Symfony demo can be nice ?

https://github.com/symfony/demo/pull/875

**Comment by javiereguiluz** [comment]
@weaverryan SymfonyCasts recently published a 35-tutorial-long !! series on file uploading in Symfony apps: https://symfonycasts.com/screencast/symfony-uploads

Now that all this file-uploading stuff is recent in your head ... could you please review the current Symfony Docs about file uploading to outline the needed changes/fixes/improvements and also tell us in which articles we could link to this new SymfonyCasts series? Thanks!

**Comment by tlarsonlgdor** [comment]
Everything looks pretty good on the Symfony Cast according to my personal experience. 
`$uploadedFile = $request->files->get('image');` 
referenced the upload-in-form part of the Symfony Cast works great! 
However, the symfony "doc" that has the error is at 
[https://symfony.com/doc/current/controller/upload_file.html](url)
It uses
`$file = $product->getBrochure();`
which does not work. This document could use a correction and it should probably reference the Symfony Cast for more information and detail.

**Comment by carsonbot** [comment]
Thank you for this issue.
There has not been a lot of activity here for a while. Has this been resolved?

**Comment by carsonbot** [comment]
Friendly ping? Should this still be open? I will close if I don't hear anything.

**Comment by carsonbot** [comment]
Hey,

I didn't hear anything so I'm going to close it. Feel free to comment if this is still relevant, I can always reopen!
